export enum ProjectCategory {
  None = 'None',
  FoodAndBeverages = 'Food and Beverages',
  Pharmaceuticals = 'Pharmaceuticals',
  Marketing = 'Marketing',
  Gaming = 'Gaming',
  Finance = 'Finance',
  Biotech = 'Biotech',
  Defence = 'Defence',
  RealEstate = 'Real Estate',
  Logistics = 'Logistics',
  Government = 'Government',
  Media = 'Media',
  Healthcare = 'Healthcare',
  Education = 'Education',
  Fashion = 'Fashion',
}
